### ISSUE TITLE
Dorobienie legendy dla wielu ngramów

### ISSUE THREAD

**Issue by siemionides** [tgrez/sejm-ngram#58]
6) Dorobienie legendy dla wielu ngramów.

Zgodnie z sugestią Iry, dla wielu ngramów checkboxy z nazwami partii powinny się zmienieć na radiobuttony. W taki sposób będzie możliwe wybranie nazwy tylko jednej partii i nasz wykres umożliwi porównanie kilku ngramów dla jednej tylko partii.

**Comment by siemionides** [comment]
Potrzebny będzie inny endpoint (chyba?)
Format dla odpowiedzi z serwera widzę jakiś taki
[
	{
		ngram: piwo,
		listdate:[ 
			{
				date:
				count
			}
		]
	},

		{
		ngram: wojna,
		listdate:[ 
			{
				date:
				count
			}
		]
	},

]

**Comment by siemionides** [comment]
Ok, here's the deal:
- po wpisaniu dwóch ngramów (pojawiają się nad wykresem) checkboxy powinny zamienić się na radiobuttony z Partiami
- po wpisaniu dwóch ngramów (drugiego albo dwóch i więcej na raz) powinniśmy używać innego call'a (/many-ngrams)
- /many-ngrams bez parametru &party= zwraca po prostu dane  dla wszytkich partii (wytłumaczone powyżej
- po kliknieciu na radiobutton partii powinny sie dane prezladowac
- w tym trybie trzeba by pokolorowac ngramy wpisane nad wyszukiwarkaw kolory odpowiadajace wykresom
-

**Comment by luntain** [comment]
fixed
