### ISSUE TITLE
Co to jest?

### ISSUE THREAD

**Issue by ad-m** [tgrez/sejm-ngram#59]
Hej,
Trafiłem na to repozytorium. Jesteście super. Będzie świetnie.

Co to jest?

Z wyrazami szacunku,

**Comment by KrzysztofMadejski** [comment]
To mój ulubiony komentarz na githubie od dziś! :+1:

**Comment by ad-m** [comment]
OK. Ty też jesteś super.

Co tutaj jest?

**Comment by KrzysztofMadejski** [comment]
Wyręczę @siemionides i odpowiem: http://epf.org.pl/pl/2014/03/14/sejmotrendy/ :)

**Comment by ad-m** [comment]
Dziękuje. Jesteś wspaniały :smiley: 

 
![zaznaczenie_098](https://cloud.githubusercontent.com/assets/3618479/6985824/9e70abb6-da37-11e4-9ce3-652ec96421e7.png)
