### ISSUE TITLE
kupić VPS'a na pół roku

### ISSUE THREAD

**Issue by siemionides** [tgrez/sejm-ngram#76]

**Comment by ad-m** [comment]
Gdzie? Czy hosting musi spełniać wymogi GIODO?

**Comment by ad-m** [comment]
Jakie wymagania co do dysku?

**Comment by siemionides** [comment]
Hej, 
już mieliśmy wcześiej dostęp do VPS'a z ovh (jakiegoś prostego, za 30 PLN brutto / miesiąc). Przedłużyłem z nimi umowę, gdyż przyda nam się VPS także do innych projektów. A musi to byś jakiś linux z dostęp po ssh, by móc trzymać tam nad-skomplikowany silnik sejmotrendó∑ ;)

**Comment by ad-m** [comment]
Ok, OVH jest ok, do momentu, gdy nie macie rejestracji w serwisie, bo to
będzie przestępstwo.

W dniu 2 września 2015 23:35 użytkownik Michał Siemiończyk <
notifications@github.com> napisał:

**Comment by siemionides** [comment]
W jakim serwisie? Co dokładnie mogłoby być przestępstwem?

**Comment by ad-m** [comment]
Udostępnienie danych osobowych użytkowników bez porozumienia, o którym
stanowi art. 31 u.o.o. Zwróc uwagę także na art. 51 u.o.d.o.

2015-09-02 23:40 GMT+02:00 Michał Siemiończyk <notifications@github.com>:

**Comment by siemionides** [comment]
Tzn. chodzi Ci o funkcję rejestracji w naszym serwisie? Jeżeli tak, to nie planujemy takiej. A jeżeli byśmy planowali i serwer stałby na OVH, to czy nie moglibyśmy w regulaminie do zaakceptowania poinformować użytkowników o konsekwencjach, na które muszą się zgodzić rejestrując się?

**Comment by ad-m** [comment]
Nie możecie uchylać ustaw regulaminem.

W dniu 3 września 2015 00:00 użytkownik Michał Siemiończyk <
notifications@github.com> napisał:

**Comment by siemionides** [comment]
Nie rozumiem - twierdzisz, ze OVH ma prawo do dostępu do tych danych, które umieszczamy na ich serwerach?

**Comment by ad-m** [comment]
Niewątpliwie ma do nich dostęp i go przechowuje, zatem przetwarza.
Przetwarzanie danych osobowych to jakiekolwiek operacje wykonywane na
danych osobowych, takie jak zbieranie, utrwalanie, przechowywanie,
opracowywanie, zmienianie, udostępnianie i usuwanie, a zwłaszcza te, które
wykonuje się w systemach informatycznych (art. 7 pkt. 2 u.o.d.o.)

 W mojej ocenie powinno się przekazać przetwarzanie określonych danych
osobowych OVH i sporządzić z OVH umowę o powierzeniu przetwarzania danych
osobywch, jeżeli wykorzystuje się infrastrukture OVH do przetwarzania
danych osobowych. Zobacz na stanowisko GIODO, które wskazuje, że nawet w
celu zniszczenia dokumentów ( http://www.giodo.gov.pl/317/id_art/3094/j/pl/
) należy z firmą niszczącą dokumenty podpisać umowę, a co dopiero w
przypadku firmy, która takie dane ma przetwarzać długotrwale.



W dniu 3 września 2015 01:09 użytkownik Michał Siemiończyk <
notifications@github.com> napisał:
